path: /content/data_prepared/yolo

train: clear_day/train/images
val:   clear_day/val/images

test_clear_dawn_dusk: clear_dawn_dusk/images
test_clear_night: clear_night/images
test_overcast_dawn_dusk: overcast_dawn_dusk/images
test_overcast_daytime: overcast_daytime/images
test_partly_cloudy_dawn_dusk: partly_cloudy_dawn_dusk/images
test_partly_cloudy_daytime: partly_cloudy_daytime/images
test_rainy_dawn_dusk: rainy_dawn_dusk/images
test_rainy_daytime: rainy_daytime/images
test_rainy_night: rainy_night/images
test_snowy_dawn_dusk: snowy_dawn_dusk/images
test_snowy_daytime: snowy_daytime/images
test_snowy_night: snowy_night/images

nc: 10

names:
  0: car
  1: person
  2: traffic sign
  3: traffic light
  4: truck
  5: bus
  6: bike
  7: rider
  8: motor
  9: train
