path: /content/bdd100k_yolo

train: clear_day/train/images

val: clear_day/val/images

test_rainy:    rainy/images
test_snowy:    snowy/images
test_night:    night/images
test_overcast: overcast/images

nc: 10

names:
  0: car
  1: person
  2: traffic sign
  3: traffic light
  4: truck
  5: bus
  6: bike
  7: rider
  8: motor
  9: train